### PR TITLE
save bookmark with folders

### PR DESCRIPTION
**Pull request by BillXiang**

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
You're supposed to use the template variable `{bookmarkFolders}` for this.

**Comment by BillXiang** [comment]
Thank you for reply, I will try it.

**Comment by BillXiang** [comment]
I have tested the new code and it works fine.

**Comment by gildas-lormeau** [comment]
But it's not supposed to be present by default in the filename template, you're supposed to add it manually via the options page.

**Comment by BillXiang** [comment]
Well, I got it! Then can we have a template variable for bookmark title?

**Pull request closed without merging**
