### PR TITLE
Add main script to allow cli to be directly installed from npm

### PR DESCRIPTION
**Pull request by pirate**
This will allow you to install the cli directly from github without having to clone first:

```bash
npm install 'https://gitpkg.now.sh/gildas-lormeau/SingleFile/cli?master'
./node_modules/.bin/single-file --help
```

To test this PR:
```bash
npm install 'https://gitpkg.now.sh/pirate/SingleFile/cli?patch-1'
# or
npm install --save 'https://gitpkg.now.sh/pirate/SingleFile/cli?66c7b9bc' --no-cache
./node_modules/.bin/single-file --help
```

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Great! Thank you so much, I did not know gitpkg.now.sh.

**Comment by gildas-lormeau** [comment]
@pirate Unfortunately, the PR does not work as expected because the structure of the project is far to be perfect. Actually, the cli depends on `../lib` folder. This is due to the fact that the project is an extension historically.

The good news is that you don't need to use gitpkg.now.sh. I moved the `package.json` file to the root folder of the project and you should be able to install SingleFile with npm by running `npm install 'gildas-lormeau/SingleFile#master'`. I'll add this procedure in the README.

**Comment by pirate** [comment]
Thanks, I actually found the same issue with the`../lib` dependency and was going to submit a patch but you beat me to it!

**Comment by gildas-lormeau** [comment]
You're welcome. I pushed some commits to make the NPM module more legit. Now the script exposed via the `main` entry is an API usable in the JS world.

**Pull request merged**
