### PR TITLE
Enable `npm install single-file --global`

### LINKED ISSUE #394: Packaging with PKG [ENHANCEMENT]
Hi @gildas-lormeau 
I'm playing with **singlefile cli** and I want to package it as a standalone executable using [PKG](https://github.com/zeit/pkg).
The idea is to put it in my `/usr/bin` and use it as a normal linux command.
I'm new to Node and hope you can advice.

Thank you.
Lou.

### PR DESCRIPTION
**Pull request by fregante**
Fixes #394 

After merging this and #413, you just need to run:

```sh
cd cli
npm publish
```

and `single-file` will be available on npm

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Thank you, I did not test your PR yet. I'm wondering if it really works since the "lib" folder is a dependency of the CLI tool but it's not a sub-folder.

**Comment by fregante** [comment]
In that case it won't work.

You have 2 options:

- publish both the lib as `single-file` and the cli as `single-file-cli`, so they can be used independently from node (best choice. Example: [is-npm](https://github.com/sindresorhus/is-npm) and [is-npm-cli](https://github.com/sindresorhus/is-npm-cli))
- move `package.json` to the root of this repo and publish it from there (you'll have to specify an [`.npmignore`](http://npm.github.io/publishing-pkgs-docs/publishing/the-npmignore-file.html) file to avoid including the extension.)

**Comment by gildas-lormeau** [comment]
I'm afraid that if I publish the "lib" folder as a separate package, people will yell at me because I do not use modules. I don't use them because:
 - Chrome does not support modules in extensions
 - Extensions depending on a build tool are always manually reviewed in Firefox. I also guess it makes the review harder. Personnally, I love using [CRX Viewer](https://robwu.nl/crxviewer/) to inspect the code of extensions I use but I hate when the code is built with webpack for example.
 - I like to debug the code as is

I did not think about using `.npmignore` though. Maybe that's the best compromise in the short term?

There's also the problem of SingleFileZ. Ideally, I would like to merge the implementation of their "lib" folders and then publish the merged code as a library.

**Comment by fregante** [comment]
You can use [UMD](https://github.com/umdjs/umd) or a simplified version of it:

```js
function singlefile () {

}
if (typeof module === 'object') {
	module.exports = singleFile;
} else {
	this.singlefile = singlefile;
}
```

This way each file in `lib` can be either `require`d or loaded exactly like you're doing now.

This enables you to publish it as an npm module without adding a build step for the extension.

**Comment by fregante** [comment]
This conversion requires more effort so I'll close this PR and let you do it if it interests you.

**Comment by gildas-lormeau** [comment]
I'm sorry

**Pull request closed without merging**
