### PR TITLE
Feature/rest form api

### PR DESCRIPTION
**Pull request by yooper**
Added Destination option for sending the page to an REST Form API endpoint.

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Thank you, it looks fine to me. Is the fact that compressed files are not supported (i.e. zip, self-extracting zip files) deliberate?

**Comment by gildas-lormeau** [comment]
I have another question. Why don't you pass directly `blob` to `formData.append()`, without creating a `File` instance in the rest-form-api module?

**Comment by yooper** [comment]
> Thank you, it looks fine to me. Is the fact that compressed files are not supported (i.e. zip, self-extracting zip files) deliberate?

It was not deliberate. Just a lack of familiarity. I can follow up with a future PR to add the feature, after I dig into the code a little more.

**Comment by yooper** [comment]
> I have another question. Why don't you pass directly `blob` to `formData.append()`, without creating a `File` instance in the rest-form-api module?

I used an approach from a previous implementation. I will try to implement using a blob directly and follow up with a future PR if it is successful.

Thank you for accepting this feature into the code base.

**Comment by gildas-lormeau** [comment]
I've just pushed the support of compressed files. Can you confirm it works fine for you? (I also removed the usage of `File`)

**Comment by yooper** [comment]
> I've just pushed the support of compressed files. Can you confirm it works fine for you? (I also removed the usage of `File`)

Yes, I can test and get you feedback before EOD.

**Comment by gildas-lormeau** [comment]
Thank you!

**Comment by yooper** [comment]
@gildas-lormeau, I tested the following format options:
- HTML -> Works as expected
- self-extracting ZIP (universal) -> The file is interpreted as HTML, but has binary code in it too
- self-extraction Zip -> The file is interpreted as HTML, but has binary code in it too
- Zip -> The file is interpreted as a zip

**Comment by gildas-lormeau** [comment]
Thank you for the feedback, that's the expected result :).

**Pull request merged**
