### PR TITLE
Editor cutting

### PR DESCRIPTION
**Pull request by egor-duda**
I've implemented a new feature for the editor. It allows selective removal of elements from the document before saving. 
When user selects "Annotate and save the page..." option and enters the editor, there is new button in the toolbar. When this button is toggled on, hovering over document outlines current element, and clicking on that element removes it from the document.
That way user can remove any cruft from the document before saving, enhancing its readability and reducing its size.

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Thank you very much for your contribution. I reviewed the changes but I did not test the implementation yet. I have 2 questions:
 - Did you test it on Firefox Android?
 - Why don't you remove the element from the DOM instead of adding the class "single-file-removed"?

**Comment by egor-duda** [comment]
>     * Did you test it on Firefox Android?
Not yet, will do.
>     * Why don't you remove the element from the DOM instead of adding the class "single-file-removed"?
So that deletions can be easily undone. I'm adding "revert deletions" functionality at the moment.

**Comment by gildas-lormeau** [comment]
For Firefox on android, I was planning that the user would be able to highlight the element it would remove (e.g. displaying the outline), the same way the shadow appears behind a note when moving it. I was also planning to reuse the code allowing to determine which element to highlight given a position (the `getTarget` function).

**Comment by egor-duda** [comment]
You mean that instead of hovering, it's better to make a draggable icon, which highlights (or outlines) an element under it, and when dropped, deletes this highlighted element?

**Comment by gildas-lormeau** [comment]
> You mean that instead of hovering, it's better to make a draggable icon, which highlights (or outlines) an element under it, and when dropped, deletes this highlighted element?

I think this would be great, I was thinking about a draggable overlay or a draggable outline without using any icon. 
However, I also consider the highlighting is not mandatory since you propose to implement a button to cancel the deletion.

**Comment by gildas-lormeau** [comment]
Thank you, I think I can merge the code. However, could you please format the code (I use the default formatting of vscode), verify there are no warning with eslint (the configuration file is in the root directory), and ensure you don't have one-letter variables or parameters like `e` in the function `cutter`?

**Comment by egor-duda** [comment]
Sure, will do.
I've noticed that for some reason my new buttons do not get tooltips from _locale/??/messages.json, I'll look into it first

**Comment by gildas-lormeau** [comment]
Thank you! For your information, I added a missing style for `img[type=button].cut-disabled` in dark theme.

**Comment by gildas-lormeau** [comment]
I also declared `cuttingMode` in the script generated by `getEmbedScript` otherwise a non-blocking error was displayed in the console when, for example, moving a note in a saved page (outside the editor).

**Comment by gildas-lormeau** [comment]
The feature in now available in the version 1.12.21 I just published on the store of Mozilla. For Chrome, I need to wait for the current pending review to be finished (version 1.12.20), then I'll be able to upload it and finally it should be available someday on the store of Chrome.

**Comment by egor-duda** [comment]
Great, thanks a lot!

**Pull request merged**
