### PR TITLE
faq: docker outputs almost everything to stdout.

### PR DESCRIPTION
**Pull request by jtagcat**
That was confusing as hell to figure out.

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
What you're describing is a bug. I was pretty sure it worked... I'll do some tests.

**Comment by jtagcat** [comment]
so --urls-list + --dump-whatever is meant to output files, not slurpable output?

**Comment by gildas-lormeau** [comment]
I guess I somehow forgot to think about this regression when I added the option `--output-directory`. By default, I want the docker image to dump the content because that's the only way to get the content without mounting a directory.
To fix this issue, I updated the README file in order to show how to use the filename template in Docker (by disabling `--dump-content`), see https://github.com/gildas-lormeau/SingleFile/commit/68a3ff68a5c76eb271fdc86df1dd7e7f43d646b8.

**Comment by jtagcat** [comment]
I guess this can be closed then. Can't test changes atm, unpaywalling my deerly paid 700 pages.

**Pull request closed without merging**
