### PR TITLE
Use optisons set filename instead of the default blob

### PR DESCRIPTION
**Pull request by fengqi**
In the current implementation, filename is not set and server received filename is "blob".

### CODE REVIEW

**Comment by fengqi** [comment]
Also, do you think REST api needs to send a HEAD request first like WebDav does?

**Comment by gildas-lormeau** [comment]
Sorry, I totally forgot your question. Do you think a HEAD request makes sense in this context?

**Comment by fengqi** [comment]
You are right, it doesn't make sense.

**Comment by gildas-lormeau** [comment]
As a result, I merged your PR as-is :)

**Pull request merged**
