### PR TITLE
Fixing misplaced tables in README.MD

### PR DESCRIPTION
**Pull request by shyn**
Invalid markdown table format.
image

### CODE REVIEW

**Comment by shyn** [comment]
The markdown table failed to render correctly. The row should be on a separate line.
What I saw from the rendered readme page:
image

And what is expected is:

| 	 | HTML (SingleFile) | HTML (SingleFileZ) | MAFF | MHTML | Webarchive(Safari) | HTML+folder | 
| --- 	 | :---: | :---: | :---: | :---: | :---: | :---:|
| Pages are saved as a single file | ✓ 	 | ✓ 	 | ✓ | ✓ | ✓ | |
| HTML and styles are minified | ✓ | ✓ 	 | | | 	 | |
| Unused HTML and styles are removed from files | ✓ | ✓ 	 | | | | 	 |
| Binary resources are not encoded in base 64 | | ✓ 	 | ✓ | | ✓ | ✓ 	 |
| Files are compressed | | ✓ 	 | ✓ | | | 	 |
| Files can be viewed without installing any extension | ✓ | ✓¹ | | ✓² | ✓³ | ✓ |
| Files can be viewed without running JavaScript | ✓ | 	 | ✓ | ✓ | ✓ | ✓ 	 |
| Files can be unzipped to extract resources and view pages | | ✓ 	 | ✓ | | | n/a |
| Files contains the text of the page (plain or formatted) which can be indexed | ✓ 	 |✓⁴ | | ✓ | ✓ 	 | ✓ 	 |

**Comment by gildas-lormeau** [comment]
Where does this screenshot comes from? I do not see this rendering bug on github.com. My problem with your PR is that you removed all the spaces that made the table readable in ASCII and I don't know in the PR what actually fixed the rendering issue.

**Comment by gildas-lormeau** [comment]
My bad, I did not see the regression on github...

**Comment by gildas-lormeau** [comment]
I fixed this regression myself because I wanted to keep it readable in ASCII. Thank you for notifying me of the problem and suggesting a correction!

**Pull request closed without merging**
