### PR TITLE
Image compression and downscaling; remove background added

### PR DESCRIPTION
**Pull request by jimmytaker**
The output .htm files can be quite big (10+MB) due to the embedded images. I added an option in Options to compress and scale down images to the size they are displayed in. The compression level is changeable by the user.

I also added an option to remove background image from the output, as often this would be the reason for a huge .htm output file.

Last I added a few comments to help with following the flow of the code, which proved quite difficult when I was first getting into it.

Note 1: I might be porting this to Firefox soon. I already have a Version that work on Firefox, but it is heavily modified, based on crossrider and still Buggy. I however, figured out all the incompatibilities in the JavaScript between this and Firefox's dialect and can rewrite the pieces in a way that is processable by both Browsers.
A question for you - will you be accepting changes geared towards Firefox compatibility or shall I work in a different repo, shall I decide to make a production Version out of what I have?

Note 2: You might be interested to know that I created an Extension (just entering Testphase) that includes a modified Version of your SingleFile (https://github.com/jimmytaker/SmartCollector.git). I do not know whether I want this yet, but I will consider it, if you are on board with the idea - extracting the SingleFile Core functionality from SmartCollector, adding SingleFile Core as a requirement (in the same way your Extension works) and adding the changes necessary for SmartCollector to SingleFile Core. Currently These are
1: the ability to produce a SingleFile AND an HTM with just the Images extracted from it and stored next to it as separate files.
2. Processing of native files (e.g. when you have a .pdf or .jpg opened in the browser)

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Hi, 
I am sorry. I was not working on the extension when you submitted the pull request. Recently, "SingleFile Core" has been removed from the store by Google so I had to rewrite it. The code is now written in ES6 with async and await to make it much more readable and maintainable. Unfortunately, your pull request cannot be merged anymore.

**Comment by Lichtenshtein** [comment]
> option to compress and scale down images to the size they are displayed in

I wish there was such an option in the extension. I had to fiddle with 7-zip exporting pictures to then compress them manually and add them back to .htm file. But now it doesn't work for some reason. To my thoughts the .htm takes up too much space because of the pictures.

**Comment by gildas-lormeau** [comment]
What kind of transform do you apply to reduce the weight of the images?

**Comment by Lichtenshtein** [comment]
> What kind of transform do you apply to reduce the weight of the images?

Nothing special... Resize images to reduce resolution; reduce the quality of jpeg, jpg images to an acceptable level/size. I do it manually in FastStone Image Viewer or IrfanView.

Perhaps some of these free projects i found might be useful to you:

jpegoptim - utility to optimize/compress JPEG files. https://github.com/tjko/jpegoptim
jpeg-archive - Utilities for archiving JPEGs for long term storage. https://github.com/danielgtaylor/jpeg-archive
Leanify - lightweight lossless file minifier/optimizer. https://github.com/JayXon/Leanify
pingo - image optimizer for web. https://css-ig.net/pingo
OptiPNG - recompresses image files to a smaller size, without losing any information. https://optipng.sourceforge.net/
mozjpeg - Improved JPEG encoder. https://github.com/mozilla/mozjpeg/

**Pull request closed without merging**
