### PR TITLE
Added complete language translations.

### PR DESCRIPTION
**Pull request by june07**
Added translations for 85 languages.

### CODE REVIEW

**Comment by gildas-lormeau** [comment]
Thank you for the contribution. Are the labels automatically translated by a service or a product?

**Comment by june07** [comment]
Yes.  Unfortunately, I don't speak that many languages.  ;)
https://webi18n.com.

**Comment by gildas-lormeau** [comment]
I hope the website will be up someday. I would like to try how good the translation is. I prefer not to add translations if the quality is debatable. From my point of view, it would degrade the image of the product. I also need to read the terms of use.

**Comment by perdolka** [comment]
I read the Ukrainian translation (/uk/) - really not bad. 
There are a few minor errors that I can fix.

**Comment by gildas-lormeau** [comment]
@perdolka Feel free to create a pull request for the ukranian translation, I would be pleased to integrate it.

**Comment by june07** [comment]
It's an unreleased service but uses machine translation on the backend (ie Google Translate).  That said, it will be at the level of quality expected from machine translation... and from my experience not quite as good as human, but a very good start.  I've used it for other projects where people then contribute small fixes/tweaks (as @perdolka) suggests.  In my opinion, it's better to have language support than not.  And having a start puts you that much closer to having native speakers contribute to polish anything that needs polish.  ;)

**Comment by gildas-lormeau** [comment]
Beyond possible translation quality problems, the problem for me is the maintenance of the extension. Translations are not fun to maintain and tend to limit me when I consider changing things in the user-interface. That's why I add them one by one. I wouldn't really want to have more than 20-30 languages.

**Pull request closed without merging**
